site_name: GrowBeam
site_url: https://eiaro.github.io/growbeam/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true  

plugins:
  - search
  - include-markdown  
  
extra_javascript:
  - overrides/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Background: background.md
  - Components: 
    - Research: components/index.md
    - Mechanical: components/mechanical.md
    - Light Sources: components/light-sources.md
    - Conclusion: components/conclusion.md
  - Design: 
    - Schematic: design/schematic.md
