name: Export and Commit KiCad Files

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    name: Export KiCad Outputs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image with KiCad 9
        run: |
          docker build -t kicad9-ci ./docker

      - name: Run Export in Docker (with absolute paths)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace kicad9-ci             bash -c "
              mkdir -p /workspace/hardware/exports &&
              kicad-cli sch export bom /workspace/hardware/kicad_project/*.kicad_sch -o /workspace/hardware/bom.csv &&
              kicad-cli sch export pdf /workspace/hardware/kicad_project/*.kicad_sch -o /workspace/hardware/exports/schematic.pdf &&
              kicad-cli pcb export gerbers /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/gerbers &&
              kicad-cli pcb export step /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/growbeam.step &&
              ls -lh /workspace/hardware && ls -lh /workspace/hardware/exports
            "

      - name: Upload export artifacts
        uses: actions/upload-artifact@v4
        with:
          name: growbeam-exports
          path: |
            hardware/bom.csv
            hardware/exports/

  commit:
    runs-on: ubuntu-latest
    needs: export
    name: Commit Exported Files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download export artifacts
        uses: actions/download-artifact@v4
        with:
          name: growbeam-exports
          path: hardware/

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Confirm required files exist
        run: |
          test -f hardware/bom.csv
          test -f hardware/exports/schematic.pdf

      - name: Commit and push exported files
        run: |
          git add -f hardware/bom.csv
          git add hardware/exports/
          git commit -m "Auto-update exported files [skip ci]" || echo "No changes to commit"
          git push
