name: Export generated KiCad Files

on:
  workflow_run:
    workflows: ["Run ERC and DRC"]
    types:
      - completed
  pull_request:
    paths:
      - 'hardware/kicad_project/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  export:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Generate Exports
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export KiCad files
        run: make export

      - name: Force Add Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --force hardware/bom.csv
          git add --force hardware/exports/schematic.pdf
          git add --force hardware/exports/gerbers
          git add --force hardware/exports/growbeam.step          
          git add --force hardware/exports/growbeam.png

      - name: Commit and Push Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto-generate files after ERC/DRC checks" || echo "No changes to commit"
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Upload exports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: growbeam-exports
          path: |
            hardware/bom.csv
            hardware/exports/
