name: Export KiCad Files and Run Checks

on:
  pull_request:
    paths:
      - 'hardware/kicad_project/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  export-and-validate:
    runs-on: ubuntu-latest
    name: Generate Exports and Run ERC/DRC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build Docker Image with KiCad 9
        run: |
          docker build -t kicad9-ci ./docker

      - name: Run ERC, DRC, and export
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace kicad9-ci bash -c "
              mkdir -p /workspace/hardware/exports &&
              kicad-cli sch run-erc /workspace/hardware/kicad_project/*.kicad_sch ||
                echo 'ERC completed with warnings or errors' &&
              kicad-cli pcb run-drc /workspace/hardware/kicad_project/*.kicad_pcb ||
                echo 'DRC completed with warnings or errors' &&
              kicad-cli sch export bom /workspace/hardware/kicad_project/*.kicad_sch -o /workspace/hardware/bom.csv &&
              kicad-cli sch export pdf /workspace/hardware/kicad_project/*.kicad_sch -o /workspace/hardware/exports/schematic.pdf &&
              kicad-cli pcb export gerbers /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/gerbers &&
              kicad-cli pcb export step /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/growbeam.step
            "

      - name: Force Add Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --force hardware/bom.csv
          git add --force hardware/exports/schematic.pdf
          git add --force hardware/exports/gerbers
          git add --force hardware/exports/growbeam.step

      - name: Commit and Push Generated Files
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generate files after ERC/DRC checks"
          branch: ${{ github.event.pull_request.head.ref }}
          title: "Update generated files"
          body: |
            This commit contains the latest automatically generated files:
            - BoM (bom.csv)
            - Schematic PDF
            - Gerbers
            - STEP model

      - name: Upload exports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: growbeam-exports
          path: |
            hardware/bom.csv
            hardware/exports/
