name: Export KiCad Files and Run Checks

on:
  pull_request:
    paths:
      - 'hardware/kicad_project/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  export-and-validate:
    runs-on: ubuntu-latest
    name: Generate Exports
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ERC, DRC, and export
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/${{ github.repository_owner }}/kicad9-ci:latest bash -c "
              mkdir -p /workspace/hardware/exports &&              
              kicad-cli sch export bom /workspace/hardware/kicad_project/*.kicad_sch -o /workspace/hardware/bom.csv &&
              kicad-cli sch export pdf /workspace/hardware/kicad_project/*.kicad_sch -o /workspace/hardware/exports/schematic.pdf &&
              kicad-cli pcb export gerbers /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/gerbers &&              
              kicad-cli pcb export step /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/growbeam.step &&
              kicad-cli pcb export vrlm /workspace/hardware/kicad_project/*.kicad_pcb -o /workspace/hardware/exports/growbeam.wrl &&
              blender -b --python render/blender_render.py
            "      

      - name: Force Add Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --force hardware/bom.csv
          git add --force hardware/exports/schematic.pdf
          git add --force hardware/exports/gerbers
          git add --force hardware/exports/growbeam.step          
          git add --force hardware/exports/growbeam.png

      - name: Commit and Push Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto-generate files after ERC/DRC checks" || echo "No changes to commit"
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Upload exports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: growbeam-exports
          path: |
            hardware/bom.csv
            hardware/exports/
